# Generated by Django 3.0.4 on 2020-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewingrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=24)),
                ('moviescore', models.DecimalField(decimal_places=1, max_digits=2)),
                ('viewingtime', models.DateField()),
                ('remarks', models.CharField(max_length=24)),
                ('impressions', models.TextField()),
            ],
        ),
    ]
