# Generated by Django 3.0.4 on 2020-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=24, verbose_name='电影名称')),
                ('moviescore', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('viewingtime', models.DateField(verbose_name='观影日期')),
                ('remarks', models.CharField(max_length=24, verbose_name='评语')),
                ('impressions', models.TextField(verbose_name='观后感')),
            ],
        ),
        migrations.DeleteModel(
            name='Viewingrecord',
        ),
    ]
