# Generated by Django 3.0.4 on 2020-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0002_auto_20200317_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=24, verbose_name='书名')),
                ('bookscore', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='理解多少')),
                ('booktimestart', models.DateField(verbose_name='开始日期')),
                ('booktimeend', models.DateField(verbose_name='结束日期')),
                ('remarks', models.CharField(max_length=24, verbose_name='评语')),
                ('impressions', models.TextField(verbose_name='观后感')),
            ],
        ),
    ]
