# Generated by Django 3.0.4 on 2020-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0004_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtype', models.CharField(max_length=24, verbose_name='技术领域')),
                ('blogtime', models.DateField(verbose_name='日期')),
                ('remarks', models.CharField(max_length=50, verbose_name='简介')),
                ('impressions', models.TextField(verbose_name='详细文档')),
            ],
        ),
    ]
